### PR TITLE
Fix npm install

### PR DESCRIPTION
**Pull request by panpansh**

### CODE REVIEW

**Comment by adonespitogo** [comment]
Thanks for your work @panpansh :)

**Comment by panpansh** [comment]
Thanks for your work too dear @adonespitogo  :)

**Comment by ghostbullet** [comment]
Why don't try to clone it out ????

Vào 10:02 PM, T.7, 16 Th2, 2019 panpansh <notifications@github.com đã viết:

**Comment by panpansh** [comment]
Iam currently working on other project

**Comment by sharipovshoxrux** [comment]
I have an error, did like u wrote

**Pull request merged**
